name: CI Flow ğŸŒŠ

on:
  pull_request:
    branches:
      - main

jobs:

  build :
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: ğŸ³ Build Docker Image
        run: docker build . --tag headofcontent.de

      - name: ğŸš§ Spin Up Application Container
        run: docker run -d -p 80:80 headofcontent.de

      - name: â¬‡ï¸ Download dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: 'http://localhost:80'
          configFile: cypress.config.cjs
          command: npx cypress run --env host=http://localhost:80
