name: Docker Image CD

on:
  pull_request:
    branches: ['main']

jobs:

  build :
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: ğŸ³ Install Dependencies
        run: yarn install

      - name: ğŸš§ Build Application
        run: yarn build

      - name: ğŸ›« Start Application
        run: yarn start
