name: Docker Image CI

on: [push]
#  pull_request:
#    branches:
#      - main

jobs:

  build :
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
    
      - name: ğŸ³ Install Dependencies
        run: yarn install

      - name: ğŸš§ Build Application
        run: yarn build

      - uses: cypress-io/github-action@v5.0.2
        with:
          start: yarn start
